### ISSUE TITLE
won_game_terms and lost_game_terms

### ISSUE THREAD

**Issue by tdry77** [pfmonville/whole_history_rating#2]
In the PlayerDay class, there are functions called won_game_terms and lost_game_terms.

Say in the won_game_terms function, for each game a player has won, we append this:

[1.0,0.0,1.0,other_gamma]

And similarly to the lost games terms, we append this:

[0.0,other_gamma,1.0,other_gamma]

Clearly I know what the gamma is as that is defined but what do the other positions/numbers in these lists represent?

**Comment by pfmonville** [comment]
Sorry I completly forgot to answer your question.
Recent notifications brought your post to me again.
Fortunately it is linked to the same question you asked to the original authors to this algorythm implementation.
Since they answer the question I’ll put a link to [their answer](https://github.com/goshrine/whole_history_rating/issues/4#issuecomment-574627436)  and close this issue.



Have a nice day.
