### ISSUE TITLE
win probabilities for all history

### ISSUE THREAD

**Issue by ioannis12** [pfmonville/whole_history_rating#3]
hello, 

congrats for your work, I was wondering if there is a way to get the win probabilities for all the history. Maybe use the history ratings to derive it? 

It would be useful to get a more precise estimate of the accuracy/mse than a train/test split

**Comment by pfmonville** [comment]
Hi,

I’m not sure I understand. Do you mean to compute win probability between two players considering all days (i.e. player 1 and player 2 have 3 days and you get something like this : probability of p1 winning over p2 = [0.34, 0.33, 0.28]) or do you mean to get the win probability for each game of a player ?

The former is a bit tricky because if you have one player with 3 days and another with 5 then the only way to show all the information is a cartesian product between all days which is too much information (and what do you do with a febrary 1st shusaku vs an october 1st shusai?)
The latter is doable but only at a day level not a game level (the gamma is computed for the day at a PlayerDay level)

If you want the latter you can do this for a player:

```python
player = whr.player_by_name("NameOfInterest")
probability_for_each_game = {
    day: [
        {game.opponent: game.black_win_probability()}
        if player == game.black_player
        else game.white_win_probability()
        for game in day.won_games + day.lost_games
    ]
    for day in player.days
}
```
you get that: 
```python
{1: [{'shusai': 0.3625550418976255}, {'shusai': 0.3625550418976255}, {'shusai': 0.3625550418976255}], 3: [{'shusai': 0.35293960920926193}], 4: [{'shusai': 0.34976985299751295}, {'shusai': 0.34976985299751295}]}
```
But if the player had several games with the same opponent the same day, it will be the same probability. So you can get rid of redundancy with this:
```python
player = whr.player_by_name("NameOfInterest")
probability_for_each_game = {
    day.day: {
        game.opponent(p1).name: game.black_win_probability()
        if player == game.black_player
        else game.white_win_probability()
        for game in day.won_games + day.lost_games
    }
    for day in player.days
}
```
which give you this:
```python
{1: {'shusai': 0.3625550418976255}, 3: {'shusai': 0.35293960920926193}, 4: {'shusai': 0.34976985299751295}}
```

I hope this helps

**Comment by ioannis12** [comment]
hello, thank you for your answer, 

I was thinking something like:

```
day1, playerA, playerB, score, win_probability
day1, playerC, playerD, score, win_probability
...
day2, playerF, playerG, score, win_probability
...
dayN, playerX, playerY, score, win_probability
```

(a player can play once in a day)

**Comment by pfmonville** [comment]
In that case, taking into account the gamma of each day, this will give you what you want:

```python
all_games_stats = [
    {
        "day": game.day,
        "black": game.bpd.player.name,
        "white": game.wpd.player.name,
        "score": game.winner,
        "black_win_probability": game.black_win_probability(),
        "white_win_probability": game.white_win_probability(),
    }
    for game in whr.games
]
```
Which will give you this
```python
[
    {
        "day": 1,
        "black": "A",
        "white": "B",
        "score": "W",
        "black_win_probability": 0.11658241946113643,
        "white_win_probability": 0.8834175805388637,
    },
    {
        "day": 1,
        "black": "C",
        "white": "D",
        "score": "W",
        "black_win_probability": 0.5769912296305897,
        "white_win_probability": 0.42300877036941037,
    },
    {
        "day": 2,
        "black": "A",
        "white": "B",
        "score": "W",
        "black_win_probability": 0.11586667492256023,
        "white_win_probability": 0.8841333250774398,
    },
    {
        "day": 2,
        "black": "C",
        "white": "D",
        "score": "B",
        "black_win_probability": 0.5801638124050592,
        "white_win_probability": 0.4198361875949407,
    },
    {
        "day": 3,
        "black": "A",
        "white": "C",
        "score": "W",
        "black_win_probability": 0.23460814070652639,
        "white_win_probability": 0.7653918592934735,
    },
    {
        "day": 3,
        "black": "B",
        "white": "D",
        "score": "B",
        "black_win_probability": 0.7653918592940584,
        "white_win_probability": 0.23460814070594166,
    },
]
```

**Comment by ioannis12** [comment]
awesome! I'll try it out soon. 

another question, the day parameter, is it a calendar days or game days?

**Comment by pfmonville** [comment]
It's supposed to be an integer but if you use the same type across all days then a datetime will work.
Same type because I'll post an update which will compare dates and will allow to add games on a previous day (which is impossible now, you have to add games in order otherwise you'll end up with [{day:1,...},{day:2,...},{day:1,...}]).

At first I just wanted this project to be a straight port from the ruby implementation but now I think a rework of the interface is needed (especially removing ruby style from the code).

So the feature you've asked may be added in it.

If you have more ideas I'll take it gladly ;)

**Comment by ioannis12** [comment]
hello, 

I had some time today and tried it out, it seems that the win_probability is after the game has been played, I was thinking about  a prediction probability before the game has been played! 

any ideas how to do that? 

kind regards

**Comment by pfmonville** [comment]
(edit) I answered too quickly.
Inedeed when using what I gave you it is using the gamma of the day but it has already been computed. I am thinking of another way to do it

**Comment by pfmonville** [comment]
When I looked into it, the gamma and elo are adjusted for all days.

So when you see a probability for a future match between p1 and p2 with 50% for each (first match) when p1 will win and you iterate to compute new elos, this probability will change in favor of p1. But I think it is normal behaviour because with new information a posteriori the real probability of winning this day is shown.

So the more matches you have the less variance in previous probabilities you have between two stable players.

Unfortunately the gamma and elo for each game at a particular time (model state) are definitively lost when you iterate with new games, so you can’t derive a history of "historic" probabilities for each game. You can only have the reestimated probabilities taking into account all information (but different for each player day).

Another way of doing it will be to add an attribute of historic_probability for each game at creation (in game.py  in __init__ add self.historic_probability = whr.probability_future_match(white, black)). 

but you have to iterate at each day added, otherwise if you add several days at once the historic probability will be from the day before you iterate

**Comment by ioannis12** [comment]
hello, 

thank you for your reply, I run the probability_future_match before each game and then the iterate/auto_iterate function, but it's pretty time consuming. 

I was hoping there was another way doing a final iterate() and using the ordered_ratings or smt like that for the predictions

**Comment by pfmonville** [comment]
Yes the quicker way would be to add an attrribute in game class to keep track of all prediction at the time there were made.
But then again, it ill work only if the data is given each day and the iteration done just after that each time.

If you don’t have another point concerning the history I’m closing this issue.

Thanks again and good day :)

**Comment by ioannis12** [comment]
Hello, 

I have another question regarding the handicap argument. 

The description says it's less than 400 elo units, if I have a league where the home team is winning on average 55% of the games, how can I translate this advantage into the handicap argument? 

kind regards

**Comment by pfmonville** [comment]
Hello,

The handicap argument should represent the adjusted rank of the handicap given in the real game.
For example, in chess if you remove one rook for player 1 then it represents a boost of 1400 elo for the player 2 (see [here](https://en.chessbase.com/post/komodo-9-odds-matches-against-gms))

Since I based this project on goshrine implementation which use it for go games, the handicap represents stones added beforehand for black player in specific positions, the first free move is played by white. With that in mind the handicap argument is how much in elo black has been helped (the first player in the game object).

Typically in a professional match of go each additional stone you give to black at the beginning represents a boost of 300 elo but it’s another value for non professionnal matches ([here](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwjGirjjhKL0AhVFzRoKHWd3BF8QFnoECBEQAw&url=https%3A%2F%2Fboardgames.stackexchange.com%2Fquestions%2F5571%2Fwhat-is-the-formula-of-rank-difference-to-handicap-stones%23%3A~%3Atext%3DThis%2520can%2520in%2520fact%2520be%2Cstone%2520differences%2520between%2520players%2520interact.&usg=AOvVaw0mbdZeTzqrBCcxahfkjyIi))

In your case either there are enough games played to alternate home teams or there are not enough games to compensate playing at home (maybe just one game).
For the former you have nothing to do,  for the latter you must know the correspondance in elo (from existing tables) or compute it from previous games (it is not trivial).

for go, if you know the rank of the players you can increase the number of handicap stones for the weaker player until there is a 50% winning chance. then you have (stronger_player_elo - other_player_elo) = elo_for_number_of_stones_given

In the case where you don’t have a neutral game (no handicap stones or both teams play away from home) you have to find two teams that have the same chance to win when they always play at the home of one of the teams.
then you make the difference of elo of both teams and you have the bonus in elo when one team plays at home. You will get a better result by averaging all the identical configurations you can find to have a global handicap bonus.

But don’t take my word for it. It is how I will start to compute something like this.
Either way good luck and have fun ^^

**Comment by ioannis12** [comment]
I had a look at the paper of remi coulom, I don't see where he is using the elo model and the elo points? His model is based on the terry bradley model.
If he is using the elo formula for prediction, you can calculate the home advantage by solving the equation for the home advantage parameter and setting the rankings equal. 
Eg. A 0.55 home advantage would be about 36 elo points.

**Comment by pfmonville** [comment]
In his paper he just mentionned that the model should handle handicap but does not have a section about it.
I said the handicap parameter is in elo because it is written like that in the goshrine implementation:
```ruby
def opponents_adjusted_gamma(player)
      black_advantage = @handicap_proc ? @handicap_proc.call(self) : @handicap   
      #puts "black_advantage = #{black_advantage}"
      
      if player == white_player
        opponent_elo = bpd.elo + black_advantage
      elsif player == black_player
        opponent_elo = wpd.elo - black_advantage
      else
        raise "No opponent for #{player.inspect}, since they're not in this game: #{self.inspect}."
      end
      rval = 10**(opponent_elo/400.0)
      if rval == 0 || rval.infinite? || rval.nan?
        raise UnstableRatingException, "bad adjusted gamma: #{inspect}"
      end
      rval
    end
```

```markdown
# WholeHistoryRating::Base#create_game arguments: black player name, white player name, winner, day number, handicap
# Handicap should generally be less than 500 elo
```

the paper and goshrine implementation use elo rating, gamma rating, natural rating
![image](https://user-images.githubusercontent.com/6918697/142851428-22baf944-6309-4b5c-bdb1-827685555e15.png)

goshrine stores natural rating as self.r and compute elo rating and gamma rating with these
```ruby
def elo(self):
        return (self.r * 400) / (math.log(10))
def gamma(self):
        return math.exp(self.r)
```

So with goshrine implementation and this one, the handicap is measured in elo.
The prediction is made with gamma rating (which seems to be standard elo prediction)
```ruby
def white_win_probability(self):
        return self.wpd.gamma() / (
            self.wpd.gamma() + self.opponents_adjusted_gamma(self.white_player)
        )

def black_win_probability(self):
    return self.bpd.gamma() / (
        self.bpd.gamma() + self.opponents_adjusted_gamma(self.black_player)
    )
```


If you have a way to get the handicap just from 55% it’s great.
If it worked feel free to share the result.

**Comment by ioannis12** [comment]
I took the elo formula for win prediction of player A:  E[A] = 1 / (1 + 10^((R_b - R_a + HFA)/400)) and set R_b - R_a = 0, 
then took E[A] as 0.55 and solved for HFA. 

I tried this on a small dataset and it seems to improve the accuracy of WHR a bit. It probably needs CV to be more precise, but the solution is around that number

I just wrote this small function to calculate it

`def HFA(E):
    return - 400 * np.log10(1/E - 1)
`

**Comment by pfmonville** [comment]
According to the hypothesis that 2 teams have the same elo and if we observe a chance of winning of 55% for the home team on average then it seems logical to use this formula and thus to obtain a handicap value of 34.86 elo.
It’s nifty ! It may be of interest to add a static function doing that.
